apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-password
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx