apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-username
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx